// <auto-generated />
using System;
using HikeJordanDotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HikeJordanDotNet.Data.Migrations
{
    [DbContext(typeof(HikeJordanDbContext))]
    [Migration("20260725000001_AddPlacesAndTrails")]
    partial class AddPlacesAndTrails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HikeJordanDotNet.Data.AppUser", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ApprovalStatus").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Password").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<string>("Role").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Destination", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("CoverImageUrl").HasMaxLength(400).HasColumnType("nvarchar(400)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.HasKey("Id");
                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.HikeListing", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("DateLabel").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("Description").IsRequired().HasMaxLength(700).HasColumnType("nvarchar(700)");
                    b.Property<string>("Difficulty").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<decimal?>("DistanceKm").HasPrecision(6, 2).HasColumnType("decimal(6,2)");
                    b.Property<int?>("DurationHours").HasColumnType("int");
                    b.Property<string>("ExcludedItems").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("GroupName").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("ImagePath").HasMaxLength(400).HasColumnType("nvarchar(400)");
                    b.Property<string>("IncludedItems").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("InstagramPage").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
                    b.Property<string>("MeetingPoint").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
                    b.Property<string>("Note").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("Organizer").IsRequired().HasMaxLength(140).HasColumnType("nvarchar(140)");
                    b.Property<string>("PaymentType").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                    b.Property<string>("Region").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("RequiredGear").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<int>("SpotsLeft").HasColumnType("int");
                    b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("TimeLabel").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("TripDate").HasColumnType("datetime2");
                    b.Property<string>("WhatsApp").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
                    b.HasKey("Id");
                    b.HasIndex("Status", "Region", "Difficulty");
                    b.ToTable("HikeListings");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.OrganizerProfile", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasMaxLength(140).HasColumnType("nvarchar(140)");
                    b.Property<string>("Note").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("PastTrips").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("Rating").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.HasKey("Id");
                    b.ToTable("OrganizerProfiles");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.OrganizerRequest", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
                    b.Property<string>("Experience").IsRequired().HasMaxLength(900).HasColumnType("nvarchar(900)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(140).HasColumnType("nvarchar(140)");
                    b.Property<string>("Regions").IsRequired().HasMaxLength(220).HasColumnType("nvarchar(220)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("WhatsApp").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.HasKey("Id");
                    b.HasIndex("Email");
                    b.ToTable("OrganizerRequests");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Partner", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ImageUrl").HasMaxLength(400).HasColumnType("nvarchar(400)");
                    b.Property<string>("InstagramPage").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(140).HasColumnType("nvarchar(140)");
                    b.HasKey("Id");
                    b.ToTable("Partners");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Place", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("NameEn").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("NameAr").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Region").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("Type").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("DescriptionEn").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("DescriptionAr").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Difficulty").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("BestSeason").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("EntryFee").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<bool>("RequiresGuide").HasColumnType("bit");
                    b.Property<bool>("FamilyFriendly").HasColumnType("bit");
                    b.Property<bool>("SwimmingAvailable").HasColumnType("bit");
                    b.Property<bool>("CampingAvailable").HasColumnType("bit");
                    b.Property<decimal?>("Latitude").HasPrecision(9, 6).HasColumnType("decimal(9,6)");
                    b.Property<decimal?>("Longitude").HasPrecision(9, 6).HasColumnType("decimal(9,6)");
                    b.Property<string>("CoverImageUrl").HasMaxLength(400).HasColumnType("nvarchar(400)");
                    b.Property<string>("SafetyInfo").IsRequired().HasMaxLength(1500).HasColumnType("nvarchar(1500)");
                    b.Property<string>("GearInfo").IsRequired().HasMaxLength(1500).HasColumnType("nvarchar(1500)");
                    b.Property<string>("HowToGetThere").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<string>("GoogleMapsUrl").HasMaxLength(400).HasColumnType("nvarchar(400)");
                    b.Property<int?>("DurationHours").HasColumnType("int");
                    b.Property<decimal?>("DistanceKm").HasPrecision(6, 2).HasColumnType("decimal(6,2)");
                    b.Property<bool>("IsPublished").HasColumnType("bit");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("IsPublished", "Region");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Places");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.ReviewFlag", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Detail").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
                    b.HasKey("Id");
                    b.ToTable("ReviewFlags");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Trail", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("PlaceId").HasColumnType("int");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Difficulty").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<decimal?>("DistanceKm").HasPrecision(6, 2).HasColumnType("decimal(6,2)");
                    b.Property<int?>("DurationHours").HasColumnType("int");
                    b.Property<int?>("ElevationGainM").HasColumnType("int");
                    b.Property<string>("StartPoint").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("EndPoint").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.HasKey("Id");
                    b.HasIndex("PlaceId");
                    b.ToTable("Trails");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.TripReview", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<int>("HikeListingId").HasColumnType("int");
                    b.Property<int>("Rating").HasColumnType("int");
                    b.Property<string>("ReviewText").IsRequired().HasMaxLength(600).HasColumnType("nvarchar(600)");
                    b.Property<string>("ReviewerName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.HasKey("Id");
                    b.HasIndex("HikeListingId", "Status");
                    b.ToTable("TripReviews");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Trail", b =>
                {
                    b.HasOne("HikeJordanDotNet.Data.Place", "Place")
                        .WithMany("Trails")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Place");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.TripReview", b =>
                {
                    b.HasOne("HikeJordanDotNet.Data.HikeListing", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Hike");
                });

            modelBuilder.Entity("HikeJordanDotNet.Data.Place", b =>
                {
                    b.Navigation("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
